import { Icon } from "@/components/IconSprite";
import { Stars } from "@/components/chrome";
import { rankLabel } from "@/lib/makeupGrade";
import { tierStars, type SieveResult } from "@/lib/metricSieve";
import type { FilmState } from "./useFilmJob";

/**
 * The AI Truth Report card.
 *
 * Before the first generation this is the static placeholder the page always
 * showed. After it, the layout is a component-for-component port of the
 * `run()` template string: rating card, evidence strip, tier ladder, the metric
 * table, the out-of-bracket flag, strengths/weaknesses, and the film section.
 *
 * Strengths and weaknesses are still derived directly from the sieve's own
 * pass/fail checks — nothing fabricated or pulled from outside data.
 */

export interface GeneratedReport {
  sieve: SieveResult;
  /** Snapshotted when the report was generated, as the original did. */
  playerNumber: string;
  stamp: string;
  film: FilmState;
}

export function TruthReportPanel({ report }: { report: GeneratedReport | null }) {
  // Generating the report replaced the whole card in Phase 15, hero strip
  // included, so the two states are rendered as alternatives rather than
  // stacked.
  return (
    <div className="card" id="report" aria-live="polite">
      {report ? <GeneratedBody report={report} /> : <PlaceholderBody />}
    </div>
  );
}

function PlaceholderBody() {
  return (
    <>
      <div className="hero-head">
        <div className="hero-head-left">
          <Icon name="shield" />
          AI TRUTH REPORT
        </div>
        <img
          className="hero-tg"
          src="/icon-32.png"
          alt=""
          style={{
            width: 20,
            height: 20,
            borderRadius: 4,
            display: "block",
            filter: "drop-shadow(0 0 6px rgba(120,160,255,.3))",
          }}
        />
      </div>
      <div className="report-in">
        <div className="report-meta">Film evaluation results appear here</div>
        <div className="film">
          <h2 style={{ marginBottom: 8 }}>
            <Icon name="play" />
            Film <span className="accent">Analysis</span>
            <span className="tag">AWAITING FILM UPLOAD</span>
          </h2>
          <div className="empty" style={{ padding: 18 }}>
            Upload game film to generate the AI Truth Report for the tracked player.
          </div>
        </div>
      </div>
    </>
  );
}

function GeneratedBody({ report }: { report: GeneratedReport }) {
  const r = report.sieve;
  const tierLabel = r.tier.replaceAll("_", " ");
  const laserCount = r.checks.filter((c) => c.laser).length;
  const passCount = r.checks.filter((c) => c.passed === true).length;
  const strengths = r.checks.filter((c) => c.passed === true);
  const weaknesses = r.checks.filter((c) => c.passed === false);

  const tierColor = r.hard_metrics_passed
    ? "var(--pass)"
    : r.is_game_changer
      ? "var(--gold-1)"
      : "var(--fail)";

  return (
    <>
      <h2>
        <Icon name="shield" />
        AI Truth <span className="accent">Report</span>
      </h2>
      <div className="report-in">
        <div className="report-meta">Generated by TruGrade AI Engine &nbsp;·&nbsp; {report.stamp}</div>

        <div className="rating-card">
          <div className="rating-label">TRUSTAR RATING</div>
          <Stars count={tierStars(r)} label={`Projected tier ${tierLabel}`} />
          <div className="banner">
            <div>
              <div className="tier-big" style={{ color: tierColor }}>
                {tierLabel}
              </div>
              <div className="tier-sub">
                {report.playerNumber ? `Player #${report.playerNumber} · ` : ""}verified measurables ·
                hard metrics {r.hard_metrics_passed ? "cleared" : "not cleared"}
              </div>
            </div>
            {r.is_game_changer ? <div className="stamp">Game Changer</div> : null}
          </div>
        </div>

        {r.checks.length ? (
          <div className="evidence-strip">
            <EvidenceStat icon="shield" label="Metrics Checked" value={r.checks.length} />
            <EvidenceStat icon="check" label="Passed" value={passCount} />
            <EvidenceStat icon="bolt" label="Laser Metrics" value={laserCount} />
            <EvidenceStat icon="star" label="Qualifying Tiers" value={r.qualifying_tiers.length} />
          </div>
        ) : null}

        <div className="ladder">
          {r.walked.map((rung) => (
            <span key={rung.tier} className={rung.passed ? "rung lit" : "rung failed"}>
              {rung.tier.replaceAll("_", " ")}
            </span>
          ))}
        </div>

        {r.qualifying_tiers.length ? (
          <div className="tier-sub" style={{ marginBottom: 8 }}>
            QUALIFIES FOR:{" "}
            {r.qualifying_tiers.map((tier) => (
              <span className="pill pass" key={tier}>
                <Icon name="check" />
                {tier.replaceAll("_", " ")}
              </span>
            ))}
          </div>
        ) : null}

        <table>
          <tbody>
            <tr>
              <th>Metric</th>
              <th>Athlete</th>
              <th>Threshold</th>
              <th>Sieve</th>
            </tr>
            {r.checks.map((c) => (
              <tr key={c.metric}>
                <td>
                  {c.label}
                  {c.laser ? (
                    <span style={{ color: "var(--laser)", fontSize: 10, fontFamily: "IBM Plex Mono" }}>
                      {" "}
                      LASER
                    </span>
                  ) : null}
                </td>
                <td className={c.laser ? "val laser" : "val"}>{c.value ?? "—"}</td>
                <td style={{ color: "var(--dim)", fontFamily: "IBM Plex Mono", fontSize: 12 }}>
                  {c.threshold}
                </td>
                <td>
                  {c.passed === true ? (
                    <span className="pill pass">
                      <Icon name="check" />
                      PASS
                    </span>
                  ) : c.passed === false ? (
                    <span className="pill fail">
                      <Icon name="x" />
                      FAIL
                    </span>
                  ) : (
                    <span className="pill na">NO DATA</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {r.is_game_changer ? (
          <div className="gc">
            <b>
              <Icon name="flag" />
              Out-of-bracket flag
            </b>
            <p>{r.game_changer_reason}</p>
          </div>
        ) : null}

        {r.checks.length ? (
          <div className="sw-grid">
            <div className="sw-card strengths">
              <h3>
                <Icon name="check" />
                Strengths
              </h3>
              <ul>
                {strengths.length ? (
                  strengths.map((c) => (
                    <li key={c.metric}>
                      <Icon name="check" />
                      {c.label}
                    </li>
                  ))
                ) : (
                  <li className="sw-empty">None cleared yet.</li>
                )}
              </ul>
            </div>
            <div className="sw-card weaknesses">
              <h3>
                <Icon name="x" />
                Weaknesses
              </h3>
              <ul>
                {weaknesses.length ? (
                  weaknesses.map((c) => (
                    <li key={c.metric}>
                      <Icon name="x" />
                      {c.label}
                    </li>
                  ))
                ) : (
                  <li className="sw-empty">No missed thresholds.</li>
                )}
              </ul>
            </div>
          </div>
        ) : null}

        <div className="film">
          <h2 style={{ marginBottom: 8 }}>
            <Icon name="play" />
            Film <span className="accent">Analysis</span> — gemini-3.5-flash
            <span className="tag">
              {report.film.mode === "live"
                ? "LIVE API RESULT"
                : report.film.mode === "error"
                  ? "GRADING FAILED"
                  : "AWAITING FILM UPLOAD"}
            </span>
          </h2>
          {report.film.analysis ? (
            <FilmAnalysisBody film={report.film} />
          ) : (
            <div className="empty" style={{ padding: 18 }}>
              No film uploaded yet — drop a clip in the Film Upload panel to populate this section.
            </div>
          )}
        </div>
      </div>
    </>
  );
}

function EvidenceStat({
  icon,
  label,
  value,
}: {
  icon: "shield" | "check" | "bolt" | "star";
  label: string;
  value: number;
}) {
  return (
    <div className="estat">
      <Icon name={icon} />
      <div>
        <div className="estat-label">{label}</div>
        <div className="estat-val">{value}</div>
      </div>
    </div>
  );
}

/** Port of `renderFilmAnalysis`. */
function FilmAnalysisBody({ film }: { film: FilmState }) {
  const analysis = film.analysis ?? {};
  const grades = analysis.film_grades ?? {};
  const flags = analysis.flags ?? [];
  const identified = analysis.player_identified;
  const note = analysis.identification_note;
  const gradeEntries = Object.entries(grades);

  return (
    <>
      <div className="filmname" style={{ margin: "0 0 8px" }}>
        {film.name}
      </div>

      {note ? (
        <div
          className="tier-sub"
          style={{ margin: "6px 0 10px", color: identified === false ? "var(--fail)" : "var(--dim)" }}
        >
          {identified === false ? (
            <>
              <Icon name="x" /> PLAYER NOT IDENTIFIED —{" "}
            </>
          ) : (
            <>
              <Icon name="check" />{" "}
            </>
          )}
          {note}
        </div>
      ) : null}

      {gradeEntries.length ? (
        <div className="stat-grid">
          {gradeEntries.map(([factor, rank]) => (
            <div
              className={rank === "GAME_CHANGER" ? "stat-tile gc" : rank === "NGE" ? "stat-tile nge" : "stat-tile"}
              key={factor}
            >
              <Icon name="bolt" className="sm" />
              <div className="stat-label">{factor}</div>
              <div className="stat-val">{rankLabel(String(rank))}</div>
            </div>
          ))}
        </div>
      ) : null}

      {identified === false ? null : flags.length ? (
        flags.map((flag, index) => (
          <div className="gc" style={{ marginTop: 10 }} key={`${flag}-${index}`}>
            <b>
              <Icon name="flag" />
              Flag
            </b>
            <p>{flag}</p>
          </div>
        ))
      ) : (
        <div className="tier-sub" style={{ marginTop: 10 }}>
          No Game-Changer or NGE-level flags on this film.
        </div>
      )}
    </>
  );
}
